/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = '#2563EB';
const tintColorDark = '#8B5CF6';

export const Colors = {
  light: {
    text: '#0F172A',
    background: '#F4F7FB',
    background2: '#EEF4FA',
    graficaHistorial: '#D9EAFE',
    tint: tintColorLight,
    icon: '#ffffff',
    tabIconDefault: '#94A3B8',
    tabIconSelected: tintColorLight,
    cardMain: '#FFFFFF',
    transaccionModal: '#FFFFFF',
    cardsMain: '#FFFFFF',
    resumenRapido: 'rgba(37, 99, 235, 0.12)',
    progressBg: '#ced7e1',
    primary: '#6366f1',
    primaryDark: '#8b5cf6',
    surface: '#FFFFFF',
    surfaceVariant: '#F8FAFC',
    border: '#E2E8F0',
  },
  dark: {
    text: '#F8FAFC',
    background: '#0b1120',
    background2: '#111827',
    graficaHistorial: '#1E293B',
    tint: tintColorDark,
    icon: '#ffffff',
    tabIconDefault: '#475569',
    tabIconSelected: tintColorDark,
    cardMain: '#111827',
    transaccionModal: '#111827',
    cardsMain: '#1E293B',
    resumenRapido: 'rgba(139, 92, 246, 0.2)',
    progressBg: '#334155',
    primary: '#34d399d0',
    primaryDark: '#10b981bb',
    surface: '#111827',
    surfaceVariant: '#1E293B',
    border: '#334155',
  },
  grey: {
    text: '#ffffff',
    background: '#151718',
    background2: '#0a0a0a',
    graficaHistorial: '#141414',
    tint: tintColorDark,
    icon: '#ffffff',
    tabIconDefault: '#3e505fff',
    tabIconSelected: tintColorDark,
    cardMain: '#0a0a0a',
    transaccionModal: '#1e1e1e',
    cardsMain: '#1C1C1E',
    resumenRapido:'rgba(255, 229, 174, 0.57)',
    progressBg: '#2a2a2a',
    primary: '#373737',
    primaryDark: '#191919',
    surface: '#0a0a0a',
    surfaceVariant: '#1c1c1f',
    border: '#303030',
  },
};
