// Auto-generated by typescript_record_browser_flow from @playwright/mcp tool calls.
// Flow: home-screen
// Dev server: http://localhost:8081
import { test, expect } from '@playwright/test';

test('home-screen', async ({ page }) => {
  await page.goto('http://localhost:8081');
  await expect(page.getByText("Server Error").first()).toBeVisible();
});
